project:
  title: "GeneticDataAnalysisSP26"
  type: website
  output-dir: docs
  render:
    - "*.qmd"

editor: source

website:
  title: "Genetic Data Analysis (Spring 2026)"
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Home"
        href: index.qmd
      - section: "Module 1: Phenotypes"
        contents:
          - lessons/1_Quarto.qmd
          - lessons/2_LinearModels.qmd
          - lessons/3_MixedModels.qmd
          - lessons/4_MoreMixedModels.qmd
          - lessons/5_AdvancedMixedModels.qmd
      - section: "Module 2: Genotypes"
        contents:
          - lessons/6_GenoData.qmd
          - lessons/7_GeneticEffects.qmd


format:
  html:
    theme: cosmo
    toc: true
    toc-float: true
    toc-depth: 4
    code-copy: true
    smooth-scroll: true
    grid:
      sidebar-width: 280px
    embed-resources: true
    self-contained-math: true
    html-math-method: mathml
